#!/usr/bin/perl
#use strict;

# Rip cd. Add artist if needed. Create album record if needed. Create track and listitem records.
# If cdtag is specified on command line don't create album record.

use DBI;
use CDDB_get qw( get_cddb );

my %config;
$config{CDDB_HOST}="freedb.freedb.org";        # set cddb host
$config{CDDB_PORT}=8880;                       # set cddb port
$config{CDDB_MODE}="cddb";                     # set cddb mode: cddb or http
$config{CD_DEVICE}="/dev/cdrom";               # set cd device

# user interaction welcome?
$config{input}=1;   # 0: ask user if more than one possibility
my %cd=get_cddb(\%config);

# If not in CDDB, ask user
if(defined $cd{title}) {

  # do something with the results

  $artist = $cd{artist};
  
  $atitle = $cd{title};
  $atitle =~ s/\(/\[/;
  $atitle =~ s/\)/\]/;
  $atitle =~ s/\"/\'/;
  
  $genre = $cd{cat};
  $cddbid = $cd{id};
  $trackno = $cd{tno};
  
  $genre = ucfirst($genre);
  
}else{
  print "No CDDB entry found.\n";
  print "CD Title? ";
  $atitle = <>;

  print "Artist? ";
  $artist = <>;

  $genre = "unknown";
  $cddbid = 0;
  $trackno = 0;

}
print "artist: $artist\n";
print "title: $atitle\n";
print "category: $genre\n";
print "cddbid: $cddbid\n";
print "trackno: $trackno\n";


$db = "music";
$host = "localhost";
$user = "wkuhns";
$pwd = "";

# connect to the database.

$dbh = DBI->connect( "DBI:mysql:$db:$host", $user, $pwd)
or die "Connecting : $DBI::errstr\n ";

# Try to find artist

$sql = "SELECT uid, title, cdtag FROM album where cddbid=\"$cddbid\"";

$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
$sth->execute or die "executing: ", $dbh->errstr;

# We should have exactly 1 or no matches. Failing rows_affected,
# we read and count the matches.
$n=0;
while ($row = $sth->fetchrow_hashref)
{
  #print $row->{'uid'},'<BR>';
  $albumid = $row->{'uid'};
  $cdtag = $row->{'cdtag'};
  $title = $row->{'title'};
  $n++;
}

if ($n != 1){
  die "Wrong number of matching albums: ", $n;
}else{
  print "Found album $cdtag: $title\n";
}
$cdtag = lc($cdtag);

chdir "/music/$cdtag";

#system "cdda2wav -Bgsx -paranoia dev=/dev/cdrom";
system "cdparanoia -B -w";

$uid = 33;
$gid=300;

#opendir $dh,"/music/$cdtag";
#print readdir $dh;

  my $n=1;
  foreach my $i ( @{$cd{track}} ) {
    $f = sprintf("%02d",$n);
    $t=$i;
    $t =~ s/\"/\'/;
    $t =~ s/\"/\'/;

    rename "/music/$cdtag/track$f.cdda.wav", "/music/$cdtag/audio_$f.wav";

    $path = "/music/$cdtag/audio_$f.wav";
    chown ($uid, $gid, $path)
    or warn ("couldn't change file $path");

    $mode = 0664;
    chmod ($mode, $path)
    or warn ("couldn't change file mode $path");


    #print "$sql\n";
    print "track $n: $i\n";
    $n++;
  }

print "\nAll Done: Reloaded $cdtag\n";


