#!/usr/bin/perl
#use strict;

# Rip cd. Add artist if needed. Create album record if needed. Create track and listitem records.
# If cdtag is specified on command line don't create album record.

use DBI;
use CDDB_get qw( get_cddb );

my %config;
$config{CDDB_HOST}="freedb.freedb.org";        # set cddb host
$config{CDDB_PORT}=8880;                       # set cddb port
$config{CDDB_MODE}="cddb";                     # set cddb mode: cddb or http
$config{CD_DEVICE}="/dev/cdrom";               # set cd device

# user interaction welcome?
$config{input}=1;   # 0: ask user if more than one possibility
my %cd=get_cddb(\%config);

# If not in CDDB, ask user
if(defined $cd{title}) {

  # do something with the results

  $artist = $cd{artist};
  
  $atitle = $cd{title};
  $atitle =~ s/\(/\[/;
  $atitle =~ s/\)/\]/;
  $atitle =~ s/\"/\'/;
  
  $genre = $cd{cat};
  $cddbid = $cd{id};
  $trackno = $cd{tno};
  
  $genre = ucfirst($genre);
  
}else{
  print "No CDDB entry found.\n";
  print "CD Title? ";
  $atitle = <>;

  print "Artist? ";
  $artist = <>;

  $genre = "Unfiled";
  $cddbid = 0;
  $trackno = 0;

}
print "artist: $artist\n";
print "title: $atitle\n";
print "category: $genre\n";
print "cddbid: $cddbid\n";
print "trackno: $trackno\n";

# die("bye bye");

mkdir "/music/upload";
chdir "/music/upload";



#my $n=1;
#foreach my $i ( @{$cd{track}} ) {
#  print "track $n: $i\n";
#  $n++;
#}

#open(cdfile,"audio.cddb") || die "Could not open audio.cddb\n";

#while(<cdfile>){
# if (/DTITLE=/) {
#   $tline = $';
#   print "$tline\n";
#   ($artist,$title) = split(/\//,$tline);
#   chomp($artist);
#   $title =~ s/^ |\t|\n//;
# }
#}

# The -Z option disables paranoia - will accept tracks with errors
#system "cdparanoia -B -w -Z";

system "cdparanoia -B -w";

$db = "jukebox";
$host = "localhost";
$user = "wkuhns";
$pwd = "";

# connect to the database.

$dbh = DBI->connect( "DBI:mysql:$db:$host", $user, $pwd)
or die "Connecting : $DBI::errstr\n ";

# Try to find artist

$sql = "SELECT uid FROM artist where dispname=\"$artist\"";

$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
$sth->execute or die "executing: ", $dbh->errstr;

# We should have exactly 1 or no matches. Failing rows_affected,
# we read and count the matches.
$n=0;
while ($row = $sth->fetchrow_hashref)
{
  #print $row->{'uid'},'<BR>';
  $artistid = $row->{'uid'};
  $n++;
}

# If we found a match, we're happy. Otherwise, insert artist into DB
if ($n){
  print "Found artist: $artistid $artist\n";
} else {
  $sql = "INSERT INTO artist (dispname) values (\"$artist\")";
  $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
  $sth->execute or die "executing: ", $dbh->errstr;
  $artistid = $sth->{'mysql_insertid'};
  print "Inserted artist: $artistid\n";
}

# Try and match genre:

$sql = "SELECT uid FROM genre where gname=\"$genre\"";

$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
$sth->execute or die "executing: ", $dbh->errstr;

# We should have exactly 1 or no matches. Failing rows_affected,
# we read and count the matches.
$n=0;
while ($row = $sth->fetchrow_hashref)
{
  #print $row->{'uid'},'<BR>';
  $genreid = $row->{'uid'};
  $n++;
}

# If we found a match, we're happy. Otherwise, insert artist into DB
if ($n){
  print "Found genre: $genreid $genre\n";
} else {
  $genreid=126;
}

# Look for album
# If we have command line arg, then look for that album
# If not, we try to match title and artist
if ($ARGV[0]){
  $cdtag = uc($ARGV[0]);
  $sql = "SELECT uid FROM album WHERE cdtag='$cdtag'";
}else{
  $sql = "SELECT album.uid FROM album,artistlink WHERE (album.uid=artistlink.albumid and artistlink.artistid=$artistid AND title=\"$atitle\")";
}
$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
$sth->execute or die "executing: ", $dbh->errstr;

# We should have exactly 1 or no matches. Failing rows_affected,
# we read and count the matches.
$n=0;
while ($row = $sth->fetchrow_hashref)
{
  #print $row->{'uid'},'<BR>';
  $albumid = $row->{'uid'};
  $n++;
}

# If we found a match, we're happy. Otherwise, insert album into DB
# Worthless cddb_get doesn't get release year.....
if ($n){
  print "Found album: $albumid $a\n";
	$cdt1 = chr($albumid % 26+65);
	$cdt2 = chr(int($albumid/676)+66);
	$cdt3 = chr(int(($albumid % 676)/26) + 65);
  $sql = "UPDATE album set cddbid='$cddbid', status = (status | 1 | 2 | 64 | 32) where uid=$albumid";
  $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
  $sth->execute or die "executing: ", $dbh->errstr;
  print "Updated album: $albumid\n";
	$cdtag = lc($cdtag);
	$cdt1 = lc($cdt1);
	$cdt2 = lc($cdt2);
	$cdt3 = lc($cdt3);
  $updating = 1;

} else {
  $sql = "INSERT INTO album (title,cddbid,cdtag,genre1,status) values (\"$atitle\",'$cddbid', 'xxx', $genreid, (1 | 2 | 64 | 32))";
  $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
  $sth->execute or die "executing: ", $dbh->errstr;
  $albumid = $sth->{'mysql_insertid'};
  print "Inserted album: $albumid\n";

	# Set cdtag
	$cdt1 = chr($albumid % 26+65);
	$cdt2 = chr(int($albumid/676)+66);
	$cdt3 = chr(int(($albumid % 676)/26) + 65);
	$cdtag = $cdt1 . $cdt2 . $cdt3;
	$sql = "UPDATE album SET cdtag='$cdtag' WHERE uid=$albumid";
	$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
	$sth->execute or die "executing: ", $dbh->errstr;
	$cdtag = lc($cdtag);
	$cdt1 = lc($cdt1);
	$cdt2 = lc($cdt2);
	$cdt3 = lc($cdt3);
	
	# Link album to artist
	
	$sql = "insert into artistlink values (NULL,$artistid,$albumid,1)";
	print "$sql \n";
	$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
	$sth->execute or die "executing: ", $dbh->errstr;
	
	# Link album to 'all albums' collection
	
	$sql = "insert into alistitem values (NULL,1,$albumid)";
	print "$sql \n";
	$sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
	$sth->execute or die "executing: ", $dbh->errstr;
  $updating = 0;
}
# Write track and listitem records
$f = sprintf("%02d",$n);

$uid = 33;
$gid=300;

# If we have CDDB....
if(defined $cd{title}) {

  if($updating == 1){
    $sql = "select track.uid from listitem,track
      where listitem.trackid=track.uid
      and listitem.albumid = $albumid";
      print "$query\n";
    $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
    $sth->execute or die "executing: ", $dbh->errstr;
    while (my @row = $sth->fetchrow_array()){
      my $trackid = $row[0];
      $query = "delete from mp3file where trackid=$trackid";
      $result = $dbh->prepare($query) or die "preparing: ",$dbh->errstr;
      $result->execute or die "executing: ", $dbh->errstr;
      #print "$query\n";
      $query = "delete from listitem where trackid=$trackid";
      $result = $dbh->prepare($query) or die "preparing: ",$dbh->errstr;
      $result->execute or die "executing: ", $dbh->errstr;
      #print "$query\n";
      $query = "delete from track where uid=$trackid";
      $result = $dbh->prepare($query) or die "preparing: ",$dbh->errstr;
      $result->execute or die "executing: ", $dbh->errstr;
      #print "$query\n";
    }
      system "rm /music/$cdt1/$cdt2/$cdt3/*.mp3";
      system "rm /music/$cdt1/$cdt2/$cdt3/*.m4a";
      system "rm /music/$cdt1/$cdt2/$cdt3/*.wav";
      system "rm /music/$cdt1/$cdt2/$cdt3/*.wma";
 }
  my $n=1;
  foreach my $i ( @{$cd{track}} ) {
    $f = sprintf("%02d",$n);
    $t=$i;
    $t =~ s/\"/\'/;
    $t =~ s/\"/\'/;

    $sql = "INSERT INTO track (artistid,title,url,genre1,seq,rating,ftype,pscore,volume) values ($artistid,\"$t\",'\/music\/$cdt1\/$cdt2\/$cdt3\/audio_$f.wav',$genreid,$n,60,1,110,0.95)";
    print "$sql \n";
    $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
    $sth->execute or die "executing: ", $dbh->errstr;
    $trackid = $sth->{'mysql_insertid'};
    $sql = "INSERT INTO listitem (trackid,albumid,seq) values ($trackid,$albumid,$n)";
    print "$sql \n";
    $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
    $sth->execute or die "executing: ", $dbh->errstr;
    $sql = "INSERT INTO talink (tid,aid,rank) values ($trackid,$artistid,1)";
    print "$sql \n";
    $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
    $sth->execute or die "executing: ", $dbh->errstr;

    rename "/music/upload/track$f.cdda.wav", "/music/upload/audio_$f.wav";

    $path = "/music/upload/audio_$f.wav";
    chown ($uid, $gid, $path)
    or warn ("couldn't change file $path");

    $mode = 0664;
    chmod ($mode, $path)
    or warn ("couldn't change file mode $path");


    #print "$sql\n";
    print "track $n: $i\n";
    $n++;
  }
}else{
  # no CDDB: use track #
  opendir $dh,"/music/upload";
  #print readdir $dh;
  $n=1;
  foreach $filename (readdir $dh) {
      $f = sprintf("%02d",$n);
    ($a,$c,$b) = split(/\./, $filename);
    if ($b eq "wav") {
      $trk = substr($filename,5,2);
      print "$n: $a; $b= $filename, trk=$trk\n";
      $trk = substr($filename,5,2);
      $i = "audio_$trk.wav";
      rename "/music/upload/$filename", "/music/upload/$i";
 
      $sql = "INSERT INTO track (artistid,title,url,genre1,seq,rating,ftype,pscore,volume) values ($artistid,'Track $n','\/music\/$cdt1\/$cdt2\/$cdt3\/audio_$f.wav',$genreid,$n,60,1,110,0.95)";
      print "$sql\n";
      $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
      $sth->execute or die "executing: ", $dbh->errstr;

      $path = "/music/upload/$i";
      chown ($uid, $gid, $path)
        or warn ("couldn't change file $path");

      $mode = 0664;
      chmod ($mode, $path)
        or warn ("couldn't change file mode $path");

      $trackid = $sth->{'mysql_insertid'};
      $sql = "INSERT INTO listitem (trackid,albumid,seq) values ($trackid,$albumid,$n)";
      $sth = $dbh->prepare($sql) or die "preparing: ",$dbh->errstr;
      $sth->execute or die "executing: ", $dbh->errstr;
      print "$sql\n";
      print "track $n: $i\n";
    $n++;

    }
  }
}

# create directory tree if needed
unless (-e "/music/$cdt1"){
  mkdir "/music/$cdt1";
}

unless (-e "/music/$cdt1/$cdt2"){
  mkdir "/music/$cdt1/$cdt2";
}

# if directory exists, copy files. else move 'upload' to new directory
if (-e "/music/$cdt1/$cdt2/$cdt3"){
	system "mv /music/upload/* /music/$cdt1/$cdt2/$cdt3/";
	system "rmdir /music/upload";
}else{
	rename "/music/upload", "/music/$cdt1/$cdt2/$cdt3";
}

$path = "/music/$cdt1/$cdt2/$cdt3";

chown ($uid, $gid, $path)
 or warn ("couldn't change file $path");

$mode = 0774;
chmod ($mode, $path)
 or warn ("couldn't change file mode $path");

system "/music/tools/coverart2 $cdtag";

print "\nAll Done: Created directory $cdt1/$cdt2/$cdt3\n";


